#!/bin/zsh

#clear csv
: > data.csv

#Number of times to run war
reps=${1:-99}

#analyze the data
function analyze {
    #set war size
    size=${1:-5}

    #run war
    for i in {1..$reps}
        ./war -s $size

    #compile parser
    javac read.java

    #run parser
    java read

    #clear csv
    : > data.csv
}

#compile war
make

analyze 2
analyze 3
analyze 4
analyze 5
analyze 6
